part of 'resource.dart';

/// Acts like a constructor, returns a [Resource], accepts a
/// [Map<String, Dynamic>] as an argument
Resource _resourceFromJson(Map<String, dynamic> json) {
  final Dstu2ResourceType? resourceType =
  resourceTypeFromStringMap[json['resourceType']];
  return switch (resourceType) {
    Dstu2ResourceType.Account => Account.fromJson(json),
    Dstu2ResourceType.AllergyIntolerance => AllergyIntolerance.fromJson(json),
    Dstu2ResourceType.Appointment => Appointment.fromJson(json),
    Dstu2ResourceType.AppointmentResponse => AppointmentResponse.fromJson(json),
    Dstu2ResourceType.AuditEvent => AuditEvent.fromJson(json),
    Dstu2ResourceType.Basic => Basic.fromJson(json),
    Dstu2ResourceType.Binary => Binary.fromJson(json),
    Dstu2ResourceType.BodySite => BodySite.fromJson(json),
    Dstu2ResourceType.Bundle => Bundle.fromJson(json),
    Dstu2ResourceType.CapabilityStatement => CapabilityStatement.fromJson(json),
    Dstu2ResourceType.CarePlan => CarePlan.fromJson(json),
    Dstu2ResourceType.Claim => Claim.fromJson(json),
    Dstu2ResourceType.ClaimResponse => ClaimResponse.fromJson(json),
    Dstu2ResourceType.ClinicalImpression => ClinicalImpression.fromJson(json),
    Dstu2ResourceType.Communication => Communication.fromJson(json),
    Dstu2ResourceType.CommunicationRequest => CommunicationRequest.fromJson(json),
    Dstu2ResourceType.Composition => Composition.fromJson(json),
    Dstu2ResourceType.ConceptMap => ConceptMap.fromJson(json),
    Dstu2ResourceType.Condition => Condition.fromJson(json),
    Dstu2ResourceType.Conformance => Conformance.fromJson(json),
    Dstu2ResourceType.Contract => Contract.fromJson(json),
    Dstu2ResourceType.Coverage => Coverage.fromJson(json),
    Dstu2ResourceType.DataElement => DataElement.fromJson(json),
    Dstu2ResourceType.DetectedIssue => DetectedIssue.fromJson(json),
    Dstu2ResourceType.Device => Device.fromJson(json),
    Dstu2ResourceType.DeviceComponent => DeviceComponent.fromJson(json),
    Dstu2ResourceType.DeviceMetric => DeviceMetric.fromJson(json),
    Dstu2ResourceType.DeviceUseRequest => DeviceUseRequest.fromJson(json),
    Dstu2ResourceType.DeviceUseStatement => DeviceUseStatement.fromJson(json),
    Dstu2ResourceType.DiagnosticOrder => DiagnosticOrder.fromJson(json),
    Dstu2ResourceType.DiagnosticReport => DiagnosticReport.fromJson(json),
    Dstu2ResourceType.DocumentManifest => DocumentManifest.fromJson(json),
    Dstu2ResourceType.DocumentReference => DocumentReference.fromJson(json),
    Dstu2ResourceType.EligibilityRequest => EligibilityRequest.fromJson(json),
    Dstu2ResourceType.EligibilityResponse => EligibilityResponse.fromJson(json),
    Dstu2ResourceType.Encounter => Encounter.fromJson(json),
    Dstu2ResourceType.EnrollmentRequest => EnrollmentRequest.fromJson(json),
    Dstu2ResourceType.EnrollmentResponse => EnrollmentResponse.fromJson(json),
    Dstu2ResourceType.EpisodeOfCare => EpisodeOfCare.fromJson(json),
    Dstu2ResourceType.ExplanationOfBenefit => ExplanationOfBenefit.fromJson(json),
    Dstu2ResourceType.FamilyMemberHistory => FamilyMemberHistory.fromJson(json),
    Dstu2ResourceType.Flag => Flag.fromJson(json),
    Dstu2ResourceType.Goal => Goal.fromJson(json),
    Dstu2ResourceType.Group => FhirGroup.fromJson(json),
    Dstu2ResourceType.HealthcareService => HealthcareService.fromJson(json),
    Dstu2ResourceType.ImagingObjectSelection => ImagingObjectSelection.fromJson(json),
    Dstu2ResourceType.ImagingStudy => ImagingStudy.fromJson(json),
    Dstu2ResourceType.Immunization => Immunization.fromJson(json),
    Dstu2ResourceType.ImmunizationRecommendation => ImmunizationRecommendation.fromJson(json),
    Dstu2ResourceType.ImplementationGuide => ImplementationGuide.fromJson(json),
    Dstu2ResourceType.List => FhirList.fromJson(json),
    Dstu2ResourceType.Location => Location.fromJson(json),
    Dstu2ResourceType.Media => Media.fromJson(json),
    Dstu2ResourceType.Medication => Medication.fromJson(json),
    Dstu2ResourceType.MedicationAdministration => MedicationAdministration.fromJson(json),
    Dstu2ResourceType.MedicationDispense => MedicationDispense.fromJson(json),
    Dstu2ResourceType.MedicationOrder => MedicationOrder.fromJson(json),
    Dstu2ResourceType.MedicationStatement => MedicationStatement.fromJson(json),
    Dstu2ResourceType.MessageHeader => MessageHeader.fromJson(json),
    Dstu2ResourceType.NamingSystem => NamingSystem.fromJson(json),
    Dstu2ResourceType.NutritionOrder => NutritionOrder.fromJson(json),
    Dstu2ResourceType.Observation => Observation.fromJson(json),
    Dstu2ResourceType.OperationDefinition => OperationDefinition.fromJson(json),
    Dstu2ResourceType.OperationOutcome => OperationOutcome.fromJson(json),
    Dstu2ResourceType.Order => Order.fromJson(json),
    Dstu2ResourceType.OrderResponse => OrderResponse.fromJson(json),
    Dstu2ResourceType.Organization => Organization.fromJson(json),
    Dstu2ResourceType.Parameters => Parameters.fromJson(json),
    Dstu2ResourceType.Patient => Patient.fromJson(json),
    Dstu2ResourceType.PaymentNotice => PaymentNotice.fromJson(json),
    Dstu2ResourceType.PaymentReconciliation => PaymentReconciliation.fromJson(json),
    Dstu2ResourceType.Person => Person.fromJson(json),
    Dstu2ResourceType.Practitioner => Practitioner.fromJson(json),
    Dstu2ResourceType.Procedure => Procedure.fromJson(json),
    Dstu2ResourceType.ProcedureRequest => ProcedureRequest.fromJson(json),
    Dstu2ResourceType.ProcessRequest => ProcessRequest.fromJson(json),
    Dstu2ResourceType.ProcessResponse => ProcessResponse.fromJson(json),
    Dstu2ResourceType.Provenance => Provenance.fromJson(json),
    Dstu2ResourceType.Questionnaire => Questionnaire.fromJson(json),
    Dstu2ResourceType.QuestionnaireResponse => QuestionnaireResponse.fromJson(json),
    Dstu2ResourceType.ReferralRequest => ReferralRequest.fromJson(json),
    Dstu2ResourceType.RelatedPerson => RelatedPerson.fromJson(json),
    Dstu2ResourceType.RiskAssessment => RiskAssessment.fromJson(json),
    Dstu2ResourceType.Schedule => Schedule.fromJson(json),
    Dstu2ResourceType.SearchParameter => SearchParameter.fromJson(json),
    Dstu2ResourceType.Slot => Slot.fromJson(json),
    Dstu2ResourceType.Specimen => Specimen.fromJson(json),
    Dstu2ResourceType.StructureDefinition => StructureDefinition.fromJson(json),
    Dstu2ResourceType.Subscription => Subscription.fromJson(json),
    Dstu2ResourceType.Substance => Substance.fromJson(json),
    Dstu2ResourceType.SupplyDelivery => SupplyDelivery.fromJson(json),
    Dstu2ResourceType.SupplyRequest => SupplyRequest.fromJson(json),
    Dstu2ResourceType.TestScript => TestScript.fromJson(json),
    Dstu2ResourceType.ValueSet => ValueSet.fromJson(json),
    Dstu2ResourceType.VisionPrescription => VisionPrescription.fromJson(json),
    _ => throw UnsupportedError(
          "You have passed Resource.fromJson a type doesn't exist or is null. "
          'In this case, the resourceType is $resourceType.')
  };
}
